/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsIntraOralDentalAssistingPrerequisitesRouteImport } from './routes/programs/intra-oral-dental-assisting-prerequisites'
import { Route as ProgramsIntraOralDentalAssistingFeesRouteImport } from './routes/programs/intra-oral-dental-assisting-fees'
import { Route as ProgramsIntraOralDentalAssistingApplyRouteImport } from './routes/programs/intra-oral-dental-assisting-apply'
import { Route as ProgramsIntraOralDentalAssistingRouteImport } from './routes/programs/intra-oral-dental-assisting'
import { Route as ProgramsDentalAssistingLevelIiPrerequisitesRouteImport } from './routes/programs/dental-assisting-level-ii-prerequisites'
import { Route as ProgramsDentalAssistingLevelIiFeesRouteImport } from './routes/programs/dental-assisting-level-ii-fees'
import { Route as ProgramsDentalAssistingLevelIiApplyRouteImport } from './routes/programs/dental-assisting-level-ii-apply'
import { Route as ProgramsDentalAssistingLevelIiRouteImport } from './routes/programs/dental-assisting-level-ii'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIntraOralDentalAssistingPrerequisitesRoute =
  ProgramsIntraOralDentalAssistingPrerequisitesRouteImport.update({
    id: '/programs/intra-oral-dental-assisting-prerequisites',
    path: '/programs/intra-oral-dental-assisting-prerequisites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsIntraOralDentalAssistingFeesRoute =
  ProgramsIntraOralDentalAssistingFeesRouteImport.update({
    id: '/programs/intra-oral-dental-assisting-fees',
    path: '/programs/intra-oral-dental-assisting-fees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsIntraOralDentalAssistingApplyRoute =
  ProgramsIntraOralDentalAssistingApplyRouteImport.update({
    id: '/programs/intra-oral-dental-assisting-apply',
    path: '/programs/intra-oral-dental-assisting-apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsIntraOralDentalAssistingRoute =
  ProgramsIntraOralDentalAssistingRouteImport.update({
    id: '/programs/intra-oral-dental-assisting',
    path: '/programs/intra-oral-dental-assisting',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsDentalAssistingLevelIiPrerequisitesRoute =
  ProgramsDentalAssistingLevelIiPrerequisitesRouteImport.update({
    id: '/programs/dental-assisting-level-ii-prerequisites',
    path: '/programs/dental-assisting-level-ii-prerequisites',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsDentalAssistingLevelIiFeesRoute =
  ProgramsDentalAssistingLevelIiFeesRouteImport.update({
    id: '/programs/dental-assisting-level-ii-fees',
    path: '/programs/dental-assisting-level-ii-fees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsDentalAssistingLevelIiApplyRoute =
  ProgramsDentalAssistingLevelIiApplyRouteImport.update({
    id: '/programs/dental-assisting-level-ii-apply',
    path: '/programs/dental-assisting-level-ii-apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsDentalAssistingLevelIiRoute =
  ProgramsDentalAssistingLevelIiRouteImport.update({
    id: '/programs/dental-assisting-level-ii',
    path: '/programs/dental-assisting-level-ii',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/faq': typeof FaqRoute
  '/testimonials': typeof TestimonialsRoute
  '/programs/dental-assisting-level-ii': typeof ProgramsDentalAssistingLevelIiRoute
  '/programs/dental-assisting-level-ii-apply': typeof ProgramsDentalAssistingLevelIiApplyRoute
  '/programs/dental-assisting-level-ii-fees': typeof ProgramsDentalAssistingLevelIiFeesRoute
  '/programs/dental-assisting-level-ii-prerequisites': typeof ProgramsDentalAssistingLevelIiPrerequisitesRoute
  '/programs/intra-oral-dental-assisting': typeof ProgramsIntraOralDentalAssistingRoute
  '/programs/intra-oral-dental-assisting-apply': typeof ProgramsIntraOralDentalAssistingApplyRoute
  '/programs/intra-oral-dental-assisting-fees': typeof ProgramsIntraOralDentalAssistingFeesRoute
  '/programs/intra-oral-dental-assisting-prerequisites': typeof ProgramsIntraOralDentalAssistingPrerequisitesRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/faq': typeof FaqRoute
  '/testimonials': typeof TestimonialsRoute
  '/programs/dental-assisting-level-ii': typeof ProgramsDentalAssistingLevelIiRoute
  '/programs/dental-assisting-level-ii-apply': typeof ProgramsDentalAssistingLevelIiApplyRoute
  '/programs/dental-assisting-level-ii-fees': typeof ProgramsDentalAssistingLevelIiFeesRoute
  '/programs/dental-assisting-level-ii-prerequisites': typeof ProgramsDentalAssistingLevelIiPrerequisitesRoute
  '/programs/intra-oral-dental-assisting': typeof ProgramsIntraOralDentalAssistingRoute
  '/programs/intra-oral-dental-assisting-apply': typeof ProgramsIntraOralDentalAssistingApplyRoute
  '/programs/intra-oral-dental-assisting-fees': typeof ProgramsIntraOralDentalAssistingFeesRoute
  '/programs/intra-oral-dental-assisting-prerequisites': typeof ProgramsIntraOralDentalAssistingPrerequisitesRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/faq': typeof FaqRoute
  '/testimonials': typeof TestimonialsRoute
  '/programs/dental-assisting-level-ii': typeof ProgramsDentalAssistingLevelIiRoute
  '/programs/dental-assisting-level-ii-apply': typeof ProgramsDentalAssistingLevelIiApplyRoute
  '/programs/dental-assisting-level-ii-fees': typeof ProgramsDentalAssistingLevelIiFeesRoute
  '/programs/dental-assisting-level-ii-prerequisites': typeof ProgramsDentalAssistingLevelIiPrerequisitesRoute
  '/programs/intra-oral-dental-assisting': typeof ProgramsIntraOralDentalAssistingRoute
  '/programs/intra-oral-dental-assisting-apply': typeof ProgramsIntraOralDentalAssistingApplyRoute
  '/programs/intra-oral-dental-assisting-fees': typeof ProgramsIntraOralDentalAssistingFeesRoute
  '/programs/intra-oral-dental-assisting-prerequisites': typeof ProgramsIntraOralDentalAssistingPrerequisitesRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/facility'
    | '/faq'
    | '/testimonials'
    | '/programs/dental-assisting-level-ii'
    | '/programs/dental-assisting-level-ii-apply'
    | '/programs/dental-assisting-level-ii-fees'
    | '/programs/dental-assisting-level-ii-prerequisites'
    | '/programs/intra-oral-dental-assisting'
    | '/programs/intra-oral-dental-assisting-apply'
    | '/programs/intra-oral-dental-assisting-fees'
    | '/programs/intra-oral-dental-assisting-prerequisites'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/facility'
    | '/faq'
    | '/testimonials'
    | '/programs/dental-assisting-level-ii'
    | '/programs/dental-assisting-level-ii-apply'
    | '/programs/dental-assisting-level-ii-fees'
    | '/programs/dental-assisting-level-ii-prerequisites'
    | '/programs/intra-oral-dental-assisting'
    | '/programs/intra-oral-dental-assisting-apply'
    | '/programs/intra-oral-dental-assisting-fees'
    | '/programs/intra-oral-dental-assisting-prerequisites'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/contact'
    | '/facility'
    | '/faq'
    | '/testimonials'
    | '/programs/dental-assisting-level-ii'
    | '/programs/dental-assisting-level-ii-apply'
    | '/programs/dental-assisting-level-ii-fees'
    | '/programs/dental-assisting-level-ii-prerequisites'
    | '/programs/intra-oral-dental-assisting'
    | '/programs/intra-oral-dental-assisting-apply'
    | '/programs/intra-oral-dental-assisting-fees'
    | '/programs/intra-oral-dental-assisting-prerequisites'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  FacilityRoute: typeof FacilityRoute
  FaqRoute: typeof FaqRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ProgramsDentalAssistingLevelIiRoute: typeof ProgramsDentalAssistingLevelIiRoute
  ProgramsDentalAssistingLevelIiApplyRoute: typeof ProgramsDentalAssistingLevelIiApplyRoute
  ProgramsDentalAssistingLevelIiFeesRoute: typeof ProgramsDentalAssistingLevelIiFeesRoute
  ProgramsDentalAssistingLevelIiPrerequisitesRoute: typeof ProgramsDentalAssistingLevelIiPrerequisitesRoute
  ProgramsIntraOralDentalAssistingRoute: typeof ProgramsIntraOralDentalAssistingRoute
  ProgramsIntraOralDentalAssistingApplyRoute: typeof ProgramsIntraOralDentalAssistingApplyRoute
  ProgramsIntraOralDentalAssistingFeesRoute: typeof ProgramsIntraOralDentalAssistingFeesRoute
  ProgramsIntraOralDentalAssistingPrerequisitesRoute: typeof ProgramsIntraOralDentalAssistingPrerequisitesRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/intra-oral-dental-assisting-prerequisites': {
      id: '/programs/intra-oral-dental-assisting-prerequisites'
      path: '/programs/intra-oral-dental-assisting-prerequisites'
      fullPath: '/programs/intra-oral-dental-assisting-prerequisites'
      preLoaderRoute: typeof ProgramsIntraOralDentalAssistingPrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/intra-oral-dental-assisting-fees': {
      id: '/programs/intra-oral-dental-assisting-fees'
      path: '/programs/intra-oral-dental-assisting-fees'
      fullPath: '/programs/intra-oral-dental-assisting-fees'
      preLoaderRoute: typeof ProgramsIntraOralDentalAssistingFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/intra-oral-dental-assisting-apply': {
      id: '/programs/intra-oral-dental-assisting-apply'
      path: '/programs/intra-oral-dental-assisting-apply'
      fullPath: '/programs/intra-oral-dental-assisting-apply'
      preLoaderRoute: typeof ProgramsIntraOralDentalAssistingApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/intra-oral-dental-assisting': {
      id: '/programs/intra-oral-dental-assisting'
      path: '/programs/intra-oral-dental-assisting'
      fullPath: '/programs/intra-oral-dental-assisting'
      preLoaderRoute: typeof ProgramsIntraOralDentalAssistingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/dental-assisting-level-ii-prerequisites': {
      id: '/programs/dental-assisting-level-ii-prerequisites'
      path: '/programs/dental-assisting-level-ii-prerequisites'
      fullPath: '/programs/dental-assisting-level-ii-prerequisites'
      preLoaderRoute: typeof ProgramsDentalAssistingLevelIiPrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/dental-assisting-level-ii-fees': {
      id: '/programs/dental-assisting-level-ii-fees'
      path: '/programs/dental-assisting-level-ii-fees'
      fullPath: '/programs/dental-assisting-level-ii-fees'
      preLoaderRoute: typeof ProgramsDentalAssistingLevelIiFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/dental-assisting-level-ii-apply': {
      id: '/programs/dental-assisting-level-ii-apply'
      path: '/programs/dental-assisting-level-ii-apply'
      fullPath: '/programs/dental-assisting-level-ii-apply'
      preLoaderRoute: typeof ProgramsDentalAssistingLevelIiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/dental-assisting-level-ii': {
      id: '/programs/dental-assisting-level-ii'
      path: '/programs/dental-assisting-level-ii'
      fullPath: '/programs/dental-assisting-level-ii'
      preLoaderRoute: typeof ProgramsDentalAssistingLevelIiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  FacilityRoute: FacilityRoute,
  FaqRoute: FaqRoute,
  TestimonialsRoute: TestimonialsRoute,
  ProgramsDentalAssistingLevelIiRoute: ProgramsDentalAssistingLevelIiRoute,
  ProgramsDentalAssistingLevelIiApplyRoute:
    ProgramsDentalAssistingLevelIiApplyRoute,
  ProgramsDentalAssistingLevelIiFeesRoute:
    ProgramsDentalAssistingLevelIiFeesRoute,
  ProgramsDentalAssistingLevelIiPrerequisitesRoute:
    ProgramsDentalAssistingLevelIiPrerequisitesRoute,
  ProgramsIntraOralDentalAssistingRoute: ProgramsIntraOralDentalAssistingRoute,
  ProgramsIntraOralDentalAssistingApplyRoute:
    ProgramsIntraOralDentalAssistingApplyRoute,
  ProgramsIntraOralDentalAssistingFeesRoute:
    ProgramsIntraOralDentalAssistingFeesRoute,
  ProgramsIntraOralDentalAssistingPrerequisitesRoute:
    ProgramsIntraOralDentalAssistingPrerequisitesRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
